config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  devise_for :users
  resources :users
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  validates :user_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      added_attrs = [ :email, :username, :password, :password_confirmation ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_post,only: [:edit,:new,:create,:update,:destroy,]

  def index
    @posts = Post.all.order(id: "DESC")
    
  end

  def new
    @post=Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def correct_post
    @post = Post.find(params[:id])
    unless @post.user.id == current_user.id
     redirect_to posts_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order(id: "DESC")
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end

  end

  private
  def user_params
    params.require(:user).permit(:username,:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>ユーザー同士でメモの共有できるサービス</h1>

<%= link_to  "新規登録", new_user_registration_path %>
<%= link_to  "ログイン", user_session_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to "ホーム",root_path %>

    <% if user_signed_in? %>
      <%= link_to  "ログアウト", destroy_user_session_path,method: :delete %>
      <%= link_to  "ユーザー一覧", users_path%>
      <%= link_to  "新規投稿" , new_post_path %>
      
    <%else%>
      <%= link_to  "新規登録", new_user_registration_path %>
      <%= link_to  "ログイン", new_user_session_path %>
    <% end %>
    
    <%= link_to "投稿一覧", posts_path %>
    
    <% if user_signed_in? %>
     <span>ユーザー名：</span>
     <%= link_to current_user,user_path(current_user.id) %>
     
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post,url: post_path(@post) do |f| %>
<p>
<%= f.text_area :content, placeholder: "メモ" %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
  <div>
    <%= post.user.username %>
    <%= post.content %>
    <% if current_user.id == post.user.id %>
        <%= link_to "編集",edit_post_path(post) %>
        <%= link_to "削除",post_path(post),method: :delete, data:{confirm: "削除しますか？"} %>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post,url: posts_path do |f| %>
<p>
<%= f.text_area :content, placeholder: "メモ" %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/index.html.erb
<h2>使っているユーザー一覧</h2>

<% @users.each do |user| %>
    
    <p>
    <%= user.username %>
    <% if current_user.id == user.id%>
      <%= link_to "ユーザー設定", edit_user_registration_path(user.id) %>

    <% end %>
    </p>

    
<% end %>

app/views/users/show.html.erb
<div>
    <span>ユーザー名：</span>
    <%= @user.username %>
</div>